// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.

package pool

import "sync"

// Pool is a generic wrapped over [sync.Pool], that also allows for a prepare function
// to be called on the value before it is returned. The zero value is safe to use.
type Pool[T any] struct {
	init     sync.Once
	internal sync.Pool

	// New optionally specifies a function to generate a value when Get would
	// otherwise return nil. It must not be changed after the first call to
	// [Pool.Get] or [Pool.Put].
	New func() T

	// Prepare optionally specifies a function to prepare a value (potentially pulled
	// from the pool) before it is returned. It must not be changed after the first
	// call to [Pool.Get] or [Pool.Put].
	Prepare func(v T) T
}

func (p *Pool[T]) ensureInit() {
	p.init.Do(func() {
		if p.New != nil {
			p.internal = sync.Pool{
				New: func() any { return p.New() },
			}
			return
		}
		p.internal = sync.Pool{
			New: func() any {
				var zero T
				return zero
			},
		}
	})
}

// Get retrieves a value from the pool. If the pool is empty, a new value is
// generated by calling [Pool.New]. If [Pool.Prepare] is not nil, it is called
// on the value before it is returned.
func (p *Pool[T]) Get() T {
	p.ensureInit()
	v := p.internal.Get()
	if p.Prepare != nil {
		return p.Prepare(v.(T)) //nolint:errcheck // Pool only stores values produced by [Pool.New] or [Pool.Put].
	}
	return v.(T) //nolint:errcheck // Pool only stores values produced by [Pool.New] or [Pool.Put].
}

// Put returns a value to the pool.
func (p *Pool[T]) Put(v T) {
	p.ensureInit()
	p.internal.Put(v)
}
