#!/bin/bash -e

PKG="${1:?usage: $0 <pkg>}"
SLUG="$(sed -r 's:/:-:g' <<<"${PKG}")"

export BASE="$(readlink -f "$(dirname "$0")/../..")"

cat <<EOF >"$BASE/.github/workflows/pkg-${SLUG}.yml"
# THIS FILE IS GENERATED BY "task workflows:all"! DO NOT EDIT!
name: pkg-${SLUG}

on:
  pull_request:
    branches: [master]
    paths: ["${PKG}/**", ".github/workflows/pkg-test-${SLUG}.yml"]
    types: [opened, edited, reopened, synchronize, unlocked]
  push:
    branches: [master]
    paths-ignore: ["${PKG}/**/*.md"]
  workflow_dispatch: {}

jobs:
  go-test:
    uses: lrstanley/.github/.github/workflows/lang-go-test-matrix.yml@master
    secrets: inherit
    with:
      num-minor: 1
      num-patch: 2
      working-directory: "${PKG}"
  go-lint:
    uses: lrstanley/.github/.github/workflows/lang-go-lint.yml@master
    secrets: inherit
    with:
      working-directory: "${PKG}"
EOF
